### ISSUE TITLE
Popup is too wide

### ISSUE THREAD

**Issue by osleg** [jsalatas/plasma-pstate#2]
Thanks for awesome widget!
The popup of the widget is a bit too wide when open, here is a screenshot 
![image](https://user-images.githubusercontent.com/207721/50534676-05efdf00-0b7b-11e9-98c1-45ba0a1bdf64.png)

**Comment by jsalatas** [comment]
Should be fixed in the code i just committed (https://github.com/jsalatas/plasma-pstate/commit/81b0155c6b67856c44f81a1ca11686b33fd64f3d). If it's still not fixed I guess I need to study Qml more than just assuming :) 

Could you please test it? Notice that you need to restart plasma for the changes to take effect.

**Comment by osleg** [comment]
Width is fixed now
